# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'asl-mobile-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'JWTDecode', '~> 3.1'
  # Pods for asl-mobile-app

  target 'asl-mobile-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'asl-mobile-appUITests' do
    # Pods for testing
  end

end
